{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3-window-size-class",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-1.3.2-multiplatform-sources.jar",
          "url": "material3-window-size-class-1.3.2-multiplatform-sources.jar",
          "size": 8813,
          "sha512": "886ee5720088242f24bad7b3b215a138d49491f001cf60af5036c74fc70360984a2e59ed143b00cde1b8b7c18d5253c61e9a5be2aaf9c0ec7975a79264282e4e",
          "sha256": "d53cacae5c02881c2a62590f384322e6e780a4ba52739b92c2b966f7525b76c1",
          "sha1": "7e9b67ba969f10f639f38235c02db7bf4af18b13",
          "md5": "45bff2e7255dd1adbb70567463b9e560"
        },
        {
          "name": "material3-window-size-class-1.3.2-samples-sources.jar",
          "url": "material3-window-size-class-1.3.2-samples-sources.jar",
          "size": 2092,
          "sha512": "a89659fde9b069c481e3868f3fd3825dd3c19bc093706a4d2369c46c9816d8765a605dccf2a6d10339f894ae99ebc0d207738eed9b6e89ef93a4397a21172e93",
          "sha256": "176db0292a93f06511220a78119e1e9f6070169fee7b09f18b1ab1475047b9a7",
          "sha1": "10e05088e8747c1697a8d1f79543c3d21b7afc71",
          "md5": "efddcc70855f89e56d4c1419eba10063"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material3-window-size-class-1.3.2-versionMetadata.json",
          "size": 2247,
          "sha512": "3c1d6b321bb9235ee988b2ca11ee3d46ee591602de1370665d210c0ed84df6e99da2d567d1c9d816577cebc13728dd2c7948cf0c7b020c2372f8d92dad9751f4",
          "sha256": "229073ceb97eb0ca70fbdb9172d3dada894bf20f58885f6ee32ee155cca03e25",
          "sha1": "a26ed319674021d75ea1aa9e092c87ac97a72344",
          "md5": "16931d3dac97c110bcdb3ad3f1487e2b"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-metadata-1.3.2.jar",
          "url": "material3-window-size-class-1.3.2.jar",
          "size": 738,
          "sha512": "7549f44a320ce7b216c7b7d516ac508e695eea02e6f8da256800a9fc81d958345d7b87e55e0a7085f330d70c77fd599610c50c39fe58ff6501f9b9c7910812d5",
          "sha256": "2507c1050a4ad2ea69d634c76c8f62e2674d62b3f9a7ed966790147ef3873d11",
          "sha1": "dd0d71e8e11819578c1cc5de45ab17f028cf056a",
          "md5": "2c68f6f1428d390712a367ece651f61e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-kotlin-1.3.2-sources.jar",
          "url": "material3-window-size-class-1.3.2-sources.jar",
          "size": 6556,
          "sha512": "32a22350b5e005fabdfc9b95f193f7e3ee7cf06e3a60625560c288b17d282e8448de49e2e4c772057fbc99696f27b971c2d095ebef0dd1f81bd6acd7461965bd",
          "sha256": "172ec2e38233257787ee8c8cf0a91ed5314bf4a0427be6b07bdb1994d09eb9c2",
          "sha1": "3c14aa8c29dd3c6256ff1da79bb1688f73818b67",
          "md5": "94b985dc0e1bec656c9a62c1aae9f7a9"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-android/1.3.2/material3-window-size-class-android-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-android",
        "version": "1.3.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-android/1.3.2/material3-window-size-class-android-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-android",
        "version": "1.3.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-android/1.3.2/material3-window-size-class-android-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-android",
        "version": "1.3.2"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-desktop/1.3.2/material3-window-size-class-desktop-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-desktop",
        "version": "1.3.2"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-desktop/1.3.2/material3-window-size-class-desktop-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-desktop",
        "version": "1.3.2"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-desktop/1.3.2/material3-window-size-class-desktop-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-desktop",
        "version": "1.3.2"
      }
    }
  ]
}