{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13624324"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.8.3-multiplatform-sources.jar",
          "url": "foundation-layout-1.8.3-multiplatform-sources.jar",
          "size": 104951,
          "sha512": "af008abdaccd588cd5a4b91eb483707929e34ce28efb8d1ab547139ac1df4cf3ee460124e4c6968bc5b485e41cf5bcaf8a002beb1927f30b78c7c90f0e0dde48",
          "sha256": "6270f8918bae651b6dd68b37c896f012a41410a82ec49db5e84e41549dc23ee5",
          "sha1": "c930e8a6d06580ea5e4ce8ac5ea00cbf0efd8510",
          "md5": "f4adacd9042ceb2b1798f6816e34e5fd"
        },
        {
          "name": "foundation-layout-1.8.3-samples-sources.jar",
          "url": "foundation-layout-1.8.3-samples-sources.jar",
          "size": 31595,
          "sha512": "cdea6c9ef1520415ebd2b3b43e8ddb60f03fdb00f6bedaf80a1669be7bec8e8e14a636ea064753a17ed468a70327854df39bc0413343f544253c789992535d55",
          "sha256": "6d2900469064221e0439645ad719a5eca5a28300f9ca5052dd1cc0bd9cb14e97",
          "sha1": "7e49e74a78b58c6ea3ef34413372c5ab8d91a072",
          "md5": "f2e45d7ad6fa571412da456cb2fde68e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "foundation-layout-1.8.3-versionMetadata.json",
          "size": 32694,
          "sha512": "964fe5db23ba0c542ec38bff17b9ba81b68d5fd761d152f107135e18a82bde1ee909a16d290cd51c16c71e7fe190a0e87b5c086f621a9a9275ff184fc19591b0",
          "sha256": "ef3659a496c45b1312443e110e7e71c842341537d91457403f333932de15b9ee",
          "sha1": "ed486ac1841fcead423f740e881fc02dd2981304",
          "md5": "65716b111a062d15f88fd78fa012ff4f"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-metadata-1.8.3.jar",
          "url": "foundation-layout-1.8.3.jar",
          "size": 36089,
          "sha512": "882b3b2b8757ea2ecaafe3e75704e15e46c8a000a3eb6a55c9aa9209a1386b56ced385fe0e3f415618035bef8cae65449dd6825818e52dbe72eda8741d43eb69",
          "sha256": "261826b42b2de8d6f9b5afa8f3c5476bbdf1e39fe640a2f278a4ae0ce9d9641b",
          "sha1": "7784c0960e355b486df0765d7b2a26b5a593ceeb",
          "md5": "1a05840b19cd9fe796ce60d4edd40762"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-kotlin-1.8.3-sources.jar",
          "url": "foundation-layout-1.8.3-sources.jar",
          "size": 91238,
          "sha512": "a1eb28128b9bd36b42f05f6b084bdb2f621d2d2e9eb87f226bcb9278c4f21e8cf7b14c587b95d88c0f92276894b8a13b61a9bac69397878fe75334b2064e30e6",
          "sha256": "1d857398f8c309fabb4ce9561d14c68e01236889d525973b2972d7fb948a3d3e",
          "sha1": "c94ce5aacde34b1cf87c5a0c8b95fcaa961b797a",
          "md5": "1d9c894939a599a75e13b9326837614a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.8.3/foundation-layout-android-1.8.3.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.8.3"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.8.3/foundation-layout-android-1.8.3.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.8.3"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.8.3/foundation-layout-android-1.8.3.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.8.3"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-jvmstubs/1.8.3/foundation-layout-jvmstubs-1.8.3.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-jvmstubs",
        "version": "1.8.3"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-jvmstubs/1.8.3/foundation-layout-jvmstubs-1.8.3.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-jvmstubs",
        "version": "1.8.3"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-jvmstubs/1.8.3/foundation-layout-jvmstubs-1.8.3.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-jvmstubs",
        "version": "1.8.3"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-layout-linuxx64stubs/1.8.3/foundation-layout-linuxx64stubs-1.8.3.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-linuxx64stubs",
        "version": "1.8.3"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-layout-linuxx64stubs/1.8.3/foundation-layout-linuxx64stubs-1.8.3.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-linuxx64stubs",
        "version": "1.8.3"
      }
    }
  ]
}