{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.webkit",
    "module": "webkit",
    "version": "1.11.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.11.0-alpha02.aar",
          "url": "webkit-1.11.0-alpha02.aar",
          "size": 162432,
          "sha512": "5dbd254b129e763adc29a4cceb9be31d6ececff60cb53870673d1ced539d175605eba6a4aa941f3042b3e0ce1b62a4c6a2358ef371ab956b3e125a5ae10b7722",
          "sha256": "3b1f5e236e9199a938fd0b507bc6ce711c46cd0286bd40a6d872de409ab7d94e",
          "sha1": "e2e5d2ca01f1b7198a667d5b2bbd3726066211d9",
          "md5": "0d9303c8c02b8a500eca5a9ee3123aff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.11.0-alpha02.aar",
          "url": "webkit-1.11.0-alpha02.aar",
          "size": 162432,
          "sha512": "5dbd254b129e763adc29a4cceb9be31d6ececff60cb53870673d1ced539d175605eba6a4aa941f3042b3e0ce1b62a4c6a2358ef371ab956b3e125a5ae10b7722",
          "sha256": "3b1f5e236e9199a938fd0b507bc6ce711c46cd0286bd40a6d872de409ab7d94e",
          "sha1": "e2e5d2ca01f1b7198a667d5b2bbd3726066211d9",
          "md5": "0d9303c8c02b8a500eca5a9ee3123aff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webkit-1.11.0-alpha02-sources.jar",
          "url": "webkit-1.11.0-alpha02-sources.jar",
          "size": 180166,
          "sha512": "b3f804237fbaf530692843300d23198fca638aa80995e4de145c22410747585a740c34aab75d7c77c46f8d96806d53f923eb684866c6e96567a19d5dd112adc7",
          "sha256": "f07339ab57bbadd85b358155fc11a065913133c702da59938ab5574ea52f466e",
          "sha1": "8f904500fb31808204cd71526806f5b0602a2d14",
          "md5": "59330dd40da64d1aa854a6d2b76f82ea"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "webkit-1.11.0-alpha02-versionMetadata.json",
          "url": "webkit-1.11.0-alpha02-versionMetadata.json",
          "size": 24136,
          "sha512": "b04bf62418fe9db5fb02987dc96ec6857adaa1ed1f13550931c53b43584a9e96f7fb4cbdec3aafb6a66cb78486a3110196a7dc3be615f1522cbfbb0484c52fa0",
          "sha256": "7f099e6fa3ddbd87f13bfe74efc68ce0e78b0450ec5e186411159c60fb19410c",
          "sha1": "b6b615f255bc6eb90d74eff4dbe792fa05890c48",
          "md5": "4189cd6a357a280e2616af5a529145ce"
        }
      ]
    }
  ]
}