{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment",
    "version": "1.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.8-sources.jar",
          "url": "fragment-1.8.8-sources.jar",
          "size": 201228,
          "sha512": "cccf7deb524ef9e6b7146f9c2885f695e7882f1041632c0f793378ed410acbab9cdab5662af92c188e71d858c1203a68fae63e569314af5dbde681576a2947f7",
          "sha256": "b8457f66090de2001104578bb2d55441ba0e582b9e0bb887897df6ae522ace80",
          "sha1": "4d5eeddf7d8d2dc079b348abd7ef9ef49140c192",
          "md5": "43de3ecd42e428c4b4ea2d305df3c882"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.8.aar",
          "url": "fragment-1.8.8.aar",
          "size": 382931,
          "sha512": "b5213f411f2d131be30341db238d2bd360fe31d17bc678f4408b2fdadaff1d580c8bccd027f09ecf33f5607a6498e640007eada35f15b77c244f85387c481ac2",
          "sha256": "7cb906956095f114eeb7769d6990f0fedc2965fc1a24368ef5eff69930c11556",
          "sha1": "d14f6046d6d372c61f13de7e3e1bc55532a33e99",
          "md5": "095fb5c1715ff841e9eebc6406282781"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.8.aar",
          "url": "fragment-1.8.8.aar",
          "size": 382931,
          "sha512": "b5213f411f2d131be30341db238d2bd360fe31d17bc678f4408b2fdadaff1d580c8bccd027f09ecf33f5607a6498e640007eada35f15b77c244f85387c481ac2",
          "sha256": "7cb906956095f114eeb7769d6990f0fedc2965fc1a24368ef5eff69930c11556",
          "sha1": "d14f6046d6d372c61f13de7e3e1bc55532a33e99",
          "md5": "095fb5c1715ff841e9eebc6406282781"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.8"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.8-versionMetadata.json",
          "url": "fragment-1.8.8-versionMetadata.json",
          "size": 37214,
          "sha512": "6e682e9fb40979f94f0e64d2ce423ac003b282c185ac17b69ae4d8ae5dfc5f717304e5fa1efc8f632228ed788f58e550860c74ed47642ac5e7578f6b2b4b46e3",
          "sha256": "e16148c9e03b61815fdac60915d806cc356bd659e9008093f425faa18771a6a6",
          "sha1": "235704725e42b90130bed31518eefbcf639a6cd7",
          "md5": "77296f8c76840e5b251cc70c17dd5900"
        }
      ]
    }
  ]
}