{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-1.3.2-multiplatform-sources.jar",
          "url": "material3-1.3.2-multiplatform-sources.jar",
          "size": 526803,
          "sha512": "bf1f06de2d0ca5fb2364473ccc8796e4d1e7f02e7d9d2ab8836e1c26662b345dab024d70b0223800fb6838c5f9fd31ab0b6adb80fb1b2ad430561ccfa0352a1d",
          "sha256": "65d2df0d622f408047301b485c008c58076867f2eb35da7e709f6dddc51e3228",
          "sha1": "afd1f5c8795f09c109c0944bd58d0d5b9ee645df",
          "md5": "173804bae4b65fbd162445ab9c2bf5fd"
        },
        {
          "name": "material3-1.3.2-samples-sources.jar",
          "url": "material3-1.3.2-samples-sources.jar",
          "size": 58300,
          "sha512": "b70c1e94c6641a463bfa5bf9ed67e0972e4b8b44ef01e76c3a28880bf76996faa97157e9e64c4b2769d2f5ef5e7993c280dcacdd05b358573aed21b457a8a1e2",
          "sha256": "3329e1a97328bbeda1e9c4f8305037ef6c13ab227af31b8ea65f757c2e791162",
          "sha1": "785900bfcf93caf2c601e44d7194f12d13deddd7",
          "md5": "74345ebc9dc3ee902fc1b71b5afe36ea"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material3-1.3.2-versionMetadata.json",
          "size": 187552,
          "sha512": "35b3d3bfb4b429b62353c2c20d5fd94d52f9cfa77626fea8e46731cb0d0e4dc0fe5ece6147ab811b913f08c8d21fdeb9b618e7d99665321ed696b8deb6d8ed32",
          "sha256": "1a2a7dea6abbef6601d8ddd188cef783b4c4305a9b517fdfdf17bc459d54fd6c",
          "sha1": "dee2ba01c517c8db7963d18806182707d995a0ab",
          "md5": "5fb5ed09a07e205287abdb1655bd0f50"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-metadata-1.3.2.jar",
          "url": "material3-1.3.2.jar",
          "size": 779,
          "sha512": "bb024903400e25f11e31b9d13575ae8870883aa974e193ff7f963be13ed55d095b38fa37be3e49a1458d699340bb6b41687b09d7573f85031ac0c209a482c88c",
          "sha256": "e2667048f898be236e8f3980d8137496bcafb626ebc4eedf32aa00f481f8fff7",
          "sha1": "441ff636812c1cad5bcfb3d084cc85d690d81144",
          "md5": "27a4d8fd017cf5c5b82a388b161e3539"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-kotlin-1.3.2-sources.jar",
          "url": "material3-1.3.2-sources.jar",
          "size": 452907,
          "sha512": "715441d74b33146e625cdca476834cdc3967057a22b0d6eeef74345e3936ace33099b11580b1e861c6eecf741fe566dc698b429372ca68fabf5713559a6e9005",
          "sha256": "28d908c089214f14e39cd63fe609a34ab246b4529f32c5197e2d6f4f57901e4d",
          "sha1": "48d42678d5be2cf6ad1ffdd9cb9bb8d645271d54",
          "md5": "1039783dd10d82c83b9d1f7aaf6017c9"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.3.2/material3-android-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.3.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.3.2/material3-android-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.3.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.3.2/material3-android-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.3.2"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.3.2/material3-desktop-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.3.2"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.3.2/material3-desktop-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.3.2"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.3.2/material3-desktop-1.3.2.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.3.2"
      }
    }
  ]
}