{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-window-size-class/1.3.1/material3-window-size-class-1.3.1.module",
    "group": "androidx.compose.material3",
    "module": "material3-window-size-class",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-release.aar",
          "url": "material3-window-size-class-android-1.3.1.aar",
          "size": 17227,
          "sha512": "d34c9dd3ec70e20449504f6ddad261fff4e122365233e8394aa9802a4bdc95e2735b0d2c78ad05f5f1132bbe00a50e8ec804d5ac1cef9ecf547f304bc534b5c9",
          "sha256": "6f9ddfe70194e3ec30ac76078c2150f6497fe6c0a711151d65d476d80a447779",
          "sha1": "ddd7bb07453f4c8fa5b4c545f42784e2944c171b",
          "md5": "d4c065df4477a118e1832ab38d828ccb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-release.aar",
          "url": "material3-window-size-class-android-1.3.1.aar",
          "size": 17227,
          "sha512": "d34c9dd3ec70e20449504f6ddad261fff4e122365233e8394aa9802a4bdc95e2735b0d2c78ad05f5f1132bbe00a50e8ec804d5ac1cef9ecf547f304bc534b5c9",
          "sha256": "6f9ddfe70194e3ec30ac76078c2150f6497fe6c0a711151d65d476d80a447779",
          "sha1": "ddd7bb07453f4c8fa5b4c545f42784e2944c171b",
          "md5": "d4c065df4477a118e1832ab38d828ccb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-1.3.1-samples-sources.jar",
          "url": "material3-window-size-class-android-1.3.1-samples-sources.jar",
          "size": 2092,
          "sha512": "a89659fde9b069c481e3868f3fd3825dd3c19bc093706a4d2369c46c9816d8765a605dccf2a6d10339f894ae99ebc0d207738eed9b6e89ef93a4397a21172e93",
          "sha256": "176db0292a93f06511220a78119e1e9f6070169fee7b09f18b1ab1475047b9a7",
          "sha1": "10e05088e8747c1697a8d1f79543c3d21b7afc71",
          "md5": "efddcc70855f89e56d4c1419eba10063"
        },
        {
          "name": "material3-window-size-class-android-1.3.1-sources.jar",
          "url": "material3-window-size-class-android-1.3.1-sources.jar",
          "size": 8475,
          "sha512": "94838017d61a1dc34578de4bea29eaddbff9b48b9dd2b4f967694dbca63c7aa5e519f3909b2e2a957a1d6112fd6824d050942ea92eb0c2454c69d94eac3e8c9a",
          "sha256": "a24f5d2867b427858fee0554af35b0dd720fff93859dd7d4bbcfe25f9991cb0e",
          "sha1": "cc0bbbb8021445acdd6f6ff3a7fceda919dda053",
          "md5": "990bbb58c8993fcd41904f7ab6df1155"
        }
      ]
    }
  ]
}