{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-api",
    "version": "1.9.23-1.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-1.9.23-1.0.19.jar",
          "url": "symbol-processing-api-1.9.23-1.0.19.jar",
          "size": 122978,
          "sha512": "fade6fed9df096da3b11e986b456b85c97481ee35d228b709cbae8ba8ab20b2b827a3954a025378b483b9d6ef20cac974534084b7da638b43e470d327b3adf9d",
          "sha256": "bee379b4495e2db2fa2f9e96432b10cebf560a8e6e7549d57a7f2822cb7a25fc",
          "sha1": "46e0fc804791fe7f78c1702b9f14669ab4dd42cc",
          "md5": "70754e8a804070d69a828f584480cf2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-1.9.23-1.0.19.jar",
          "url": "symbol-processing-api-1.9.23-1.0.19.jar",
          "size": 122978,
          "sha512": "fade6fed9df096da3b11e986b456b85c97481ee35d228b709cbae8ba8ab20b2b827a3954a025378b483b9d6ef20cac974534084b7da638b43e470d327b3adf9d",
          "sha256": "bee379b4495e2db2fa2f9e96432b10cebf560a8e6e7549d57a7f2822cb7a25fc",
          "sha1": "46e0fc804791fe7f78c1702b9f14669ab4dd42cc",
          "md5": "70754e8a804070d69a828f584480cf2a"
        }
      ]
    }
  ]
}
